#!/bin/sh
# Gatekeeper installation script for Alpine Linux LXC containers.
set -eu

DATA_DIR="/var/lib/gatekeeper"
CONF_DIR="/etc/gatekeeper"
BIN_DIR="/usr/local/bin"
DNSMASQ_DIR="${CONF_DIR}/dnsmasq"

echo "Installing Gatekeeper on Alpine..."

# Check root.
if [ "$(id -u)" -ne 0 ]; then
    echo "Error: must run as root" >&2
    exit 1
fi

# Install build and runtime dependencies.
echo "Installing packages..."
apk add --no-cache go make nftables dnsmasq iproute2 openssl wireguard-tools bash >/dev/null 2>&1 || true

# Create directories.
mkdir -p \
    "${DATA_DIR}" "${DATA_DIR}/rulesets" "${DATA_DIR}/plugins" \
    "${CONF_DIR}" "${CONF_DIR}/tls" "${DNSMASQ_DIR}" \
    /var/log/gatekeeper /run/gatekeeper

# Build from source if binaries not present.
if [ ! -f bin/gatekeeperd ]; then
    echo "Building from source..."
    make build
fi

# Copy binaries.
cp bin/gatekeeperd "${BIN_DIR}/gatekeeperd"
cp bin/gk "${BIN_DIR}/gk"
chmod +x "${BIN_DIR}/gatekeeperd" "${BIN_DIR}/gk"

# Generate API key if not exists.
if [ ! -f "${CONF_DIR}/api.key" ]; then
    head -c 32 /dev/urandom | base64 | tr -d '/+=' | head -c 32 > "${CONF_DIR}/api.key"
    chmod 600 "${CONF_DIR}/api.key"
    echo "API key generated: ${CONF_DIR}/api.key"
fi

# Generate self-signed TLS certificate if not exists.
if [ ! -f "${CONF_DIR}/tls/server.crt" ]; then
    HOSTNAME=$(hostname -f 2>/dev/null || hostname)
    openssl req -x509 -newkey ec -pkeyopt ec_paramgen_curve:prime256v1 \
        -keyout "${CONF_DIR}/tls/server.key" \
        -out "${CONF_DIR}/tls/server.crt" \
        -days 3650 -nodes \
        -subj "/CN=${HOSTNAME}/O=Gatekeeper" \
        -addext "subjectAltName=DNS:${HOSTNAME},DNS:localhost,IP:127.0.0.1" \
        2>/dev/null
    chmod 600 "${CONF_DIR}/tls/server.key"
    echo "TLS certificate generated for ${HOSTNAME}"
fi

# Install OpenRC init script.
cp init/gatekeeperd.openrc /etc/init.d/gatekeeperd 2>/dev/null \
    || cp /root/gatekeeper/init/gatekeeperd.openrc /etc/init.d/gatekeeperd 2>/dev/null \
    || true
chmod +x /etc/init.d/gatekeeperd

# Install logrotate config for daemon log rotation.
apk add --no-cache logrotate >/dev/null 2>&1 || true
cp init/gatekeeperd.logrotate /etc/logrotate.d/gatekeeperd 2>/dev/null \
    || cp /root/gatekeeper/init/gatekeeperd.logrotate /etc/logrotate.d/gatekeeperd 2>/dev/null \
    || true

# Disable Alpine's default dnsmasq — gatekeeper manages its own config.
rc-update del dnsmasq default 2>/dev/null || true
rc-service dnsmasq stop 2>/dev/null || true

# Configure dnsmasq to use gatekeeper's config directory.
# Alpine's dnsmasq default reads /etc/dnsmasq.conf; we override it.
cat > /etc/dnsmasq.conf <<DNSEOF
# Managed by Gatekeeper — do not edit.
# Actual config is generated by gatekeeperd into ${DNSMASQ_DIR}/
conf-dir=${DNSMASQ_DIR}/,*.conf
DNSEOF

# Enable IP forwarding.
if ! grep -q "net.ipv4.ip_forward=1" /etc/sysctl.conf 2>/dev/null; then
    echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
fi
sysctl -w net.ipv4.ip_forward=1 >/dev/null 2>&1 || true

# Enable and start services.
rc-update add gatekeeperd default

echo ""
echo "Gatekeeper installed successfully."
echo ""
echo "  Start:    rc-service gatekeeperd start"
echo "  Status:   rc-service gatekeeperd status"
echo "  API key:  cat ${CONF_DIR}/api.key"
echo "  CLI:      gk status"
echo "  Web UI:   https://$(hostname):8080"
echo ""
